# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Dice2Win' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Dice2Win

  pod 'React', :path => '../node_modules/react-native',:subspecs => [
	'Core',
  	'CxxBridge',
  	'RCTText',
  	'RCTNetwork',
  	'RCTWebSocket',
  	'RCTImage',
  	'RCTNetwork',
  	'DevSupport'
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'JPushRN', :path => '../node_modules/jpush-react-native'
  pod 'JCoreRN', :path => '../node_modules/jcore-react-native'




  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'RNReactNativeHapticFeedback', :path => '../node_modules/react-native-haptic-feedback'

#  pod 'react-native-aes', :path => '../node_modules/react-native-aes-crypto'

#  pod 'react-native-config', :path => '../node_modules/react-native-config'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'Dice2WinTests' do
    inherit! :search_paths
    # Pods for testing
  end

  post_install do |installer|
      installer.pods_project.targets.each do |target|

          # The following is needed to ensure the "archive" step works in XCode.
          # It removes React & Yoga from the Pods project, as it is already included in the main project.
          # Without this, you'd see errors when you archive like:
          # "Multiple commands produce ... libReact.a"
          # "Multiple commands produce ... libyoga.a"

          targets_to_ignore = %w(React yoga)

          if targets_to_ignore.include? target.name
              target.remove_from_project
          end

          if target.name == 'react-native-config'
            phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
            phase.shell_script = "cd ../../"\
                                 " && RNC_ROOT=./node_modules/react-native-config/"\
                                 " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
                                 " && export BUILD_DIR=$RNC_ROOT/ios/ReactNativeConfig"\
                                 " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.ruby"

            target.build_phases << phase
            target.build_phases.move(phase,0)
          end


      end
  end


end

target 'Dice2Win-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Dice2Win-tvOS

  target 'Dice2Win-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
