# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dice2Win' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Dice2Win

  pod 'React', :path => '../node_modules/react-native',:subspecs => [
	'Core',
  	'CxxBridge',
  	'RCTText',
  	'RCTNetwork',
  	'RCTWebSocket',
  	'RCTImage',
  	'RCTNetwork',
  	'DevSupport'
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'JPushRN', :path => '../node_modules/jpush-react-native'
  pod 'JCoreRN', :path => '../node_modules/jcore-react-native'

  target 'Dice2WinTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          
          # The following is needed to ensure the "archive" step works in XCode.
          # It removes React & Yoga from the Pods project, as it is already included in the main project.
          # Without this, you'd see errors when you archive like:
          # "Multiple commands produce ... libReact.a"
          # "Multiple commands produce ... libyoga.a"
          
          targets_to_ignore = %w(React yoga)
          
          if targets_to_ignore.include? target.name
              target.remove_from_project
          end
          
      end
  end
  

end

target 'Dice2Win-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Dice2Win-tvOS

  target 'Dice2Win-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
