# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dice2Win' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Dice2Win

  pod 'React', :path => '../node_modules/react-native',:subspecs => [
  'DevSupport',
  'RCTNetwork',
  'RCTSettings',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket'
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'JPushRN', :path => '../node_modules/jpush-react-native'
  pod 'JCoreRN', :path => '../node_modules/jcore-react-native'

  target 'Dice2WinTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Dice2Win-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Dice2Win-tvOS

  target 'Dice2Win-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
